### PR TITLE
2021 07 01 update

### PR DESCRIPTION
**Pull request by richard-thonig**
add new data and some new data categories

### CODE REVIEW

**Comment by richard-thonig** [comment]
Hi @timtroendle 
I'm not sure if the problem is the bunch of chinese characters I added, or if fritionless has a problem with guessing the right encoding. I made sure that everything is in UTF-8 without BOM so I'm fairly sure that there is no encoding problem. Plus, position 143 is new text I added, but its only latin alphabet. 
Sorry, if this is a hustle.

**Comment by timtroendle** [comment]
Oh no, _that_ problem again? I don't understand it really -- it also works completely fine on my machine. I suggest to ignore goodtables.io. We don't really need it as we have the GitHub action workflow that runs the check. I switched it off and now everything looks fine.

I also merged master into this branch which doesn't really make sense but which also doesn't do harm.

**Comment by timtroendle** [comment]
Do you want me to review your changes?

**Comment by richard-thonig** [comment]
> 
> 
> Do you want me to review your changes?

i think it should be fine.

**Pull request merged**
