### PR TITLE
Add link to Google Maps

### PR DESCRIPTION
**Pull request by timtroendle**
I've added links to Google maps to the data table.

However, this is impacted by #66. I added some cleaning routines, but didn't manage to cover all issues of the "Location_coordinates" column. I suggest to not merge this before #66 is fixed.

### CODE REVIEW

**Comment by timtroendle** [comment]
This is a simplified version of #41 .

**Comment by timtroendle** [comment]
The table is now too broad. It works fine on larger screens, but on my tablet, it doesn't fit on the screen.

**Comment by richard-thonig** [comment]
a) The map appears in the "map view" of google map instead of the sattelite view. ist there maybe the right keyword missing?
b) is there a way to strip "spaces" from the search term. It seems to fail, for the very first link because of spaces.

**Comment by timtroendle** [comment]
a) I did not find a way for that unfortunately. I think it's not possible.
b) I do remove whitespace, but this is non-breaking whitespace, see #66. Instead of trying to fix this here, I think we should rather fix the data.

**Comment by richard-thonig** [comment]
right. 
a) yes. seems to be a problem with using search, vs explicitly pointing to a location
b) fixed it in the new version.

**Review by richard-thonig — APPROVED** [review]

**Comment by richard-thonig** [comment]
@timtroendle In the new version of the data I changed them to consistently use decimal point i.e  -27.734,23.063
This should allow us  to use the explicit formating and satelite as well as zoom parameters in the google-maps link?

**Comment by timtroendle** [comment]
I will look into it after #64 is merged.

**Comment by richard-thonig** [comment]
@timtroendle in the website update PR, I saw that the first collumn seems to be broken:
maybe this can be fixed in this PR as well?
grafik

**Comment by timtroendle** [comment]
Did you rename the "name" field?

**Comment by timtroendle** [comment]
For reference: this is the descrption of Googles API:

https://developers.google.com/maps/documentation/urls/get-started

**Comment by timtroendle** [comment]
@richard-thonig Can you review this again? With locations given in decimals now, this should work better than before.

**Review by richard-thonig — CHANGES_REQUESTED** [review]
I think we should use the explicit version of the link. I gave it shot and it worked. Hurray!

**Comment by timtroendle** [comment]
Very nice. Looks great!

**Pull request merged**
