### PR TITLE
Website 2022 07 01

### PR DESCRIPTION
**Pull request by richard-thonig**
update data on website

### CODE REVIEW

**Comment by richard-thonig** [comment]
@timtroendle could you have a quick look at this next week? Netlify seems to produce an internal error. I didn't change anything besides merging in some new data, which theoretically shouldn't break anything.
Thx!

**Comment by richard-thonig** [comment]
Today, I triggered a rebuild and it seems to have worked.

**Comment by richard-thonig** [comment]
@timtroendle it looks better today, than on Friday. Only #95 remains.

**Comment by timtroendle** [comment]
As you suggested, fixing the encoding seems to have solved the problem.

**Comment by timtroendle** [comment]
The encoding must be fixed on the `master` branch, too, otherwise the data will be published with the wrong encoding.

**Comment by timtroendle** [comment]
I cannot find the comment with your question, but the answer is: VS Code.

**Pull request merged**
