### PR TITLE
Update website and new zenodo link and doi for 2020-07-01

### PR DESCRIPTION
**Pull request by richard-thonig**
add new zenodo link
add new data

### CODE REVIEW

**Comment by richard-thonig** [comment]
Seems to work:
https://deploy-preview-69--csp-guru.netlify.app/

**Comment by richard-thonig** [comment]
Wait, there is more:
grafik

**Comment by richard-thonig** [comment]
seems to work:

grafik

**Comment by timtroendle** [comment]
Perfect! And good idea to merge master into this branch. There were still some things you wanted to to here, right? Or is this mergable now?

**Comment by timtroendle** [comment]
Looks good in general. There is one issue with the data file however: it is encoded in "UTF-8 with BOM" instead of the standard "UTF-8" which causes a problem with the website and also with some other tools.

We ran into this issue [at least once before](https://github.com/repolicy/csp-guru/pull/24#discussion_r208604962), and I have no idea why it keeps reappearing. Some of your tools must reencode the data which is absolutely nasty as it is difficult to spot (and our CI doesn't detect it).

I cannot recall running into this issue in any other project. Are you using any obscure tool? As mentioned in the above link, not even Excel is encoding using UTF8 with BOM.

**Review by timtroendle — APPROVED** [review]

**Comment by timtroendle** [comment]
I fixed the problem on this branch, and opened #75 which will fix it on master. Unfortunately, the data is already released on Zenodo so people downloading the data there may run into similar issues.

**Pull request merged**
