### PR TITLE
Update data on Website

### PR DESCRIPTION
**Pull request by richard-thonig**
THe website branch needs the most recent data.

### CODE REVIEW

**Comment by richard-thonig** [comment]
Mhm, its broken.
1:51:07 PM: /usr/local/bin/build: line 34: jekyll: command not found
1:51:07 PM: Skipping functions preparation step: no functions directory set
1:51:07 PM: Caching artifacts
1:51:08 PM: failed during stage 'building site': Build script returned non-zero exit code: 127

**Comment by richard-thonig** [comment]
Maybe it has to do with changing the title in the json form openCSP to CSP.guru?
Probabbly needs to be changed in some config, too?

**Comment by timtroendle** [comment]
It says `jekyll: command not found` which means it has nothing to do with the changes. If it cannot find jekyll nothing will work of course. Maybe it was just a hickup -- can you trigger a rebuild?

**Comment by richard-thonig** [comment]
Triggered rebuild, it failed again. 
The docs say it may be a missing gemfile, but we do have one. Although its still says something about gh-pages. am i on the wrong branch somehow once again?
Command not found
"If your build fails with jekyll: command not found or gulp: command not found or anything in that pattern, it means that the software required for that command hasn’t been installed in your build. You can tell the buildbot to install the software you need by including the proper configuration file, like a Gemfile for Ruby programs like jekyll, or package.json for Node programs like gulp." https://docs.netlify.com/configure-builds/troubleshooting-tips/#command-not-found

**Comment by timtroendle** [comment]
Ok that's weird. In any case, it seems it's about time that we fix #39. I can have a look at that later.

**Pull request closed without merging**
