### PR TITLE
Remove BOM from data file

### PR DESCRIPTION
**Pull request by timtroendle**
This removes the BOM from the data file. Instead of "UTF8 with BOM" the data is now encoded in plain "UTF8".

The BOM causes issues with software that cannot handle it properly. This includes our website and some tools I am using to analyse data. Adding BOM to UTF8 is [not recommended by the Unicode Standard](https://en.wikipedia.org/wiki/Byte_order_mark#cite_note-4).

### CODE REVIEW

**Comment by richard-thonig** [comment]
what the hell is BOM?
Sorry about this.

**Review by richard-thonig — COMMENTED** [review]
looks good

**Comment by richard-thonig** [comment]
does this mean we should redo the release on zenodo?

**Comment by timtroendle** [comment]
I don't know. I guess there are worse things than that. For the next release, this should be considered however.

**Pull request merged**
